# Generated by Django 5.1.2 on 2025-10-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200)),
                ('patient_age', models.IntegerField()),
                ('patient_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('chief_complaint', models.TextField()),
                ('symptoms_description', models.TextField()),
                ('duration', models.CharField(max_length=100)),
                ('vital_signs', models.TextField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('management', models.TextField(blank=True, null=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('luo', 'Dholuo (Luo)'), ('kam', 'Kikamba'), ('kik', 'Kikuyu'), ('luh', 'Luhya')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
        ),
    ]
