# Generated by Django 5.2.8 on 2025-11-07 18:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('total_consultations', models.IntegerField(default=0)),
                ('consultations_by_language', models.JSONField(default=dict)),
                ('top_diagnoses', models.JSONField(default=list)),
                ('avg_processing_time', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('groq', 'Groq'), ('together', 'Together AI'), ('custom', 'Custom Provider')], default='groq', max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_url', models.URLField(default='https://api.groq.com/openai/v1/chat/completions', help_text='API endpoint URL', max_length=500)),
                ('model_name', models.CharField(choices=[('gpt-4o-mini', 'OpenAI GPT-4o Mini'), ('gpt-4o', 'OpenAI GPT-4o'), ('claude-3-5-haiku-20241022', 'Claude 3.5 Haiku'), ('claude-3-5-sonnet-20241022', 'Claude 3.5 Sonnet'), ('llama-3.1-8b-instant', 'Groq Llama 3.1 8B'), ('llama-3.1-70b-versatile', 'Groq Llama 3.1 70B'), ('mixtral-8x7b-32768', 'Groq Mixtral 8x7B'), ('custom', 'Custom Model')], default='llama-3.1-8b-instant', max_length=100)),
                ('custom_model_name', models.CharField(blank=True, help_text='Used when model_name is "custom"', max_length=100)),
                ('temperature', models.FloatField(default=0.3, help_text='Model temperature (0.0 - 1.0). Lower = more focused')),
                ('max_tokens', models.IntegerField(default=2000, help_text='Maximum tokens in response')),
                ('enable_notifications', models.BooleanField(default=True)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('luo', 'Dholuo (Luo)'), ('kam', 'Kikamba'), ('kik', 'Kikuyu'), ('luh', 'Luhya')], default='en', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['-created_at'], name='consultatio_created_f5405e_idx'),
        ),
        migrations.AddIndex(
            model_name='consultation',
            index=models.Index(fields=['patient_name'], name='consultatio_patient_05eea1_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['-date'], name='consultatio_date_d25c28_idx'),
        ),
    ]
