# Generated by Django 5.2.8 on 2025-11-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_analyticssnapshot_systemsettings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemsettings',
            old_name='api_key',
            new_name='model_path',
        ),
        migrations.RemoveField(
            model_name='analyticssnapshot',
            name='avg_processing_time',
        ),
        migrations.RemoveField(
            model_name='analyticssnapshot',
            name='top_diagnoses',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='api_provider',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='api_url',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='custom_model_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='enable_notifications',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='max_tokens',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_input_length',
            field=models.IntegerField(default=512),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='max_output_length',
            field=models.IntegerField(default=1024),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='model_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('luo', 'Dholuo (Luo)'), ('kam', 'Kikamba'), ('kik', 'Kikuyu'), ('luh', 'Luhya'), ('ma', 'Maasai')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('luo', 'Dholuo (Luo)'), ('kam', 'Kikamba'), ('kik', 'Kikuyu'), ('luh', 'Luhya'), ('ma', 'Maasai')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
