# Generated by Django 5.2.8 on 2026-01-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_rename_api_key_systemsettings_model_path_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='consultation',
            name='consultatio_patient_05eea1_idx',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='medical_history',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_age',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_gender',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='symptoms_description',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='vital_signs',
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinical_case',
            field=models.TextField(default='', help_text='Full clinical case narrative including symptoms, history, and observations.'),
            preserve_default=False,
        ),
    ]
