# Generated by Django 5.2.8 on 2026-01-19 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_remove_consultation_consultatio_patient_05eea1_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Duration of Symptoms'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='patient_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Patient ID'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='default_language',
            field=models.CharField(choices=[('en', 'English')], default='en', max_length=10),
        ),
    ]
