# Generated by Django 5.2.8 on 2026-01-24 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_consultation_original_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='min_output_length',
            field=models.IntegerField(default=150, help_text='Forces model to write long enough to include management steps'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='repetition_penalty',
            field=models.FloatField(default=1.3),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='max_output_length',
            field=models.IntegerField(default=450),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='temperature',
            field=models.FloatField(default=0.6),
        ),
    ]
