# Generated by Django 5.2.8 on 2026-01-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_systemsettings_min_output_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Linked Patient ID from Clinic App', max_length=50, null=True),
        ),
    ]
